config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'statics#home'

  # Static
  get '/about', to: 'statics#about'
  get '/faq', to: 'statics#faq'
  post '/control', to: 'statics#control'

  # Contact
  get '/contact', to: 'contact#show'
  post '/contact', to: 'contact#deliver'

  # Service
  resources :services, only: [:index, :show] do
    get ':item', item: /[^\/]+/, on: :member, to: 'services#item', as: :item
  end

  # Article
  resources :articles, only: [:index, :show] do
    get 'range/:year(/:month(/:day))', year: /[\d]{4}/, month: /[\d]{1,2}/, day: /[\d]{1,2}/,
        on: :collection, to: 'articles#index', as: :range
  end

  # Partner
  resources :partners, only: [:index]

  # Devise
  devise_for :users #, ActiveAdmin::Devise.config

  # Active Admin
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :read_local, only: :show

  def index
    @title = t 'service.index.title'
    @keywords = t 'service.index.keywords', default: ''
    @description = t 'service.index.description', default: ''
    @header = t 'service.index.header'
  end

  def show
    begin
      render params[:id]
    rescue ActionView::MissingTemplate
      raise ActionController::RoutingError.new "Service [#{params[:id]}] Not Found"
    end
  end

  def item
    begin
      render File.join 'services', params[:id], params[:item]
    rescue ActionView::MissingTemplate
      raise ActionController::RoutingError.new "Service [#{params[:id]}] Item [#{params[:item]}] Not Found"
    end
  end

  private

  def read_local
    case params[:id]
      when 'accreditation'
        @accreditation ||= YAML.load_file 'db/local/accreditation.yml'
    end
  end

end

app/views/services/aside/_accreditation.html.slim
section.m-b-2
  .headline
    h3.title: span.icon.icon-attestat[aria-hidden='true']

  ul.nav.nav-pills.nav-stacked.card
    - _path = item_service_path('accreditation', 'expert')
    li.nav-item[class=(request.path == _path && 'active' || nil)]
      a.nav-link[href=_path] = t 'service.accreditation.expert.label'
    - _path = item_service_path('accreditation', 'agency')
    li.nav-item[class=(request.path == _path && 'active' || nil)]
      a.nav-link[href=_path] = t 'service.accreditation.agency.label'
    - _path = item_service_path('accreditation', 'laboratory')
    li.nav-item[class=(request.path == _path && 'active' || nil)]
      a.nav-link[href=_path] = t 'service.accreditation.laboratory.label'
    - _path = item_service_path('accreditation', 'competence')
    li.nav-item[class=(request.path == _path && 'active' || nil)]
      a.nav-link[href=_path] = t 'service.accreditation.competence.label'