config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'statics#home'

  # Static
  get '/about', to: 'statics#about'
  get '/faq', to: 'statics#faq'
  post '/control', to: 'statics#control'

  # Contact
  get '/contact', to: 'contact#show'
  post '/contact', to: 'contact#deliver'

  # Service
  resources :services, only: [:index, :show] do
    get ':item', item: /[^\/]+/, on: :member, to: 'services#item', as: :item
  end

  # Article
  resources :articles, only: [:index, :show] do
    get 'range/:year(/:month(/:day))', year: /[\d]{4}/, month: /[\d]{1,2}/, day: /[\d]{1,2}/,
        on: :collection, to: 'articles#index', as: :range
  end

  # Partner
  resources :partners, only: [:index]

  # Devise
  devise_for :users #, ActiveAdmin::Devise.config

  # Active Admin
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Devise
  # before_action :devise_configure_permitted_parameters, if: :devise_controller?

  # private

  # Devise
  # def devise_configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :address])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_control.html.slim
ruby:
  params = request.params[:control] || {}


form#form-control.form-search.clearfix[
  method='post'
  action=control_path
]
  = hidden_field_tag :authenticity_token, form_authenticity_token

  .input-group
    input&text#control-number.form-control[
      name='control[number]'
      title=t('static.control.title')
      pattern='[Rr][Uu]\.[Нн][Цц][Сс][Сс]\.([А-Яа-я]{2}\.\d{3}|\d{3}\.\d{3}\.\d{1}\.[А-Яа-я]{2}\.\d{5})'
      placeholder=t('static.control.placeholder')
      required
      value=params[:name]
    ]
    .input-group-btn
      button&submit.btn.btn-link.text-href: span.icon.icon-search-validate[aria-hidden='true']

app/views/application/_footer.html.slim
- cache do
  footer#footer
    .wrapper
      .container
        .side-add.side-left.side-lock.side-caret
          .copyright
            a.engine.ir.m-r-1.hidden-xs-down[
              rel='nofollow'
              href='//rubyonrails.org/'
              target='_blank'
              ] Ruby on Rails
            span%copyrightYear> = DateTime.now.year
            ' &copy;
            span%copyrightHolder
              a%author.h-text--href[
                href='//fref.ru?rel=author'
                target='_blank'
                ] FREF


        .side-prime.side-right.side-lock
          .credits
            .row
              .col-xs-12.col-sm-9.col-md-8.col-lg-7.col-xl-6
                = render 'control'

              .col-xs-12.col-sm-3.col-md-4.col-lg-5.col-xl-6.text-xs-right.hidden-xs-down
                - if YANDEX[:metrika] && current_user && current_user.staff?
                  span.icon.icon-yandex-metrika.onclick.m-r-1[
                    aria-hidden='true'
                    data-ymet=YANDEX[:metrika]
                    ]
                span.icon.icon-w3c.onclick[
                  aria-hidden='true'
                  data-w3c=true
                  ]

app/views/application/_head.html.slim
- cache do
  meta[
    name='viewport'
    content= 'width=device-width, initial-scale=1'
    ]

  / Disable tap highlight on IE
  meta[
    name='msapplication-tap-highlight'
    content='no'
    ]

  / Web Application Manifest
  link[
    rel='manifest'
    href='/manifest.json'
    ]

  / Add to homescreen for Chrome on Android
  meta[
    name='mobile-web-app-capable'
    content='yes'
    ]
  meta[
    name='application-name'
    content='ncsc'
    ]
  link[
    rel='icon'
    sizes='192x192'
    href='/images/touch/android-chrome-192x192.png'
    ]

  / Add to homescreen for Safari on iOS
  meta[
    name='apple-mobile-web-app-capable'
    content='yes'
    ]
  meta[
    name='apple-mobile-web-app-status-bar-style'
    content='black'
    ]
  meta[
    name='apple-mobile-web-app-title'
    content='National Center for Standardization and Certification'
    ]
  link[
    rel='apple-touch-icon'
    href='/images/touch/apple-touch-icon-152x152.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='57x57'
    href='/images/touch/apple-touch-icon-57x57.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='60x60'
    href='/images/touch/apple-touch-icon-60x60.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='72x72'
    href='/images/touch/apple-touch-icon-72x72.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='76x76'
    href='/images/touch/apple-touch-icon-76x76.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='114x114'
    href='/images/touch/apple-touch-icon-114x114.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='120x120'
    href='/images/touch/apple-touch-icon-120x120.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='144x144'
    href='/images/touch/apple-touch-icon-144x144.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='152x152'
    href='/images/touch/apple-touch-icon-152x152.png'
    ]
  /link[
    rel='apple-touch-icon'
    sizes='180x180'
    href='/images/touch/apple-touch-icon-180x180.png'
    ]
  /link[
    rel='mask-icon'
    href='/images/touch/safari-pinned-tab.svg'
    data-color='#5bbad5'
    ]


  / Tile icon for Win8 (144x144 + tile color)
  meta[
    name='msapplication-TileImage'
    content='/images/touch/mstile-144x144.png'
    ]
  meta[
    name='msapplication-TileColor'
    content='#2f3ba2'
    ]


  / Color the status bar on mobile devices
  meta[
    name='theme-color'
    content='#2f3ba2'
    ]


  / Favicon
  /link[
    rel='icon'
    type='image/png'
    sizes='16x16'
    href='/images/icons/favicon-16x16.png'
    ]
  /link[
    rel='icon'
    type='image/png'
    sizes='32x32'
    href='/images/icons/favicon-32x32.png'
    ]
  /link[
    rel='icon'
    type='image/png'
    sizes='96x96'
    href='/images/icons/favicon-96x96.png'
    ]
  /link[rel='icon'
    type='image/png'
    sizes='192x192'
    href='/images/icons/android-chrome-192x192.png'
    ]


  = csrf_meta_tags
  /= action_cable_meta_tag

  link[
    rel='stylesheet'
    href='//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700'
    data-turbolinks-track='reload'
    ]

  = stylesheet_link_tag 'application', 'data-turbolinks-track' => 'reload'

  = touchevents_script_tag

  = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

  /[if lt IE 9]
    script[
      src='/javascripts/html5bility.min.js'
      data-turbolinks-track='reload'
      ]
  /[if lt IE 11]
    script[
      src='/javascripts/flexibility.min.js'
      data-turbolinks-track='reload'
      ]

  = yandex_metrika_script_tag

app/views/application/_header.html.slim
ruby:
  def brand
    request.path == root_path ?
      {tag: 'span', class: 'brand'} :
      {tag: 'a', href: root_path, class: 'brand text-href'}
  end


header#header.clearfix.m-b-1
  .side-add.side-left.hidden-md-down
    *brand
      | Национальный Центр
      br
      | Сертификации и
      br
      | Стандартизации

  .side-prime.side-right
    = render 'navbar'

    .row
      .col-xs-12.col-sm-6
        = render 'yandex.search'
      .col-xs-12.col-sm-6.text-sm-right
        a.icon-pseudo.icon-phone.text-href[href="tel://#{strip_tags(LOCAL[:phone]).tr(' ()-', '')}"] == LOCAL[:phone]

    address.text-md-right
      a.icon-pseudo.icon-map-marker.text-href[
        rel="nofollow"
        href=LOCAL[:address][:url]
        target='_blank'
      ] == LOCAL[:address][:text]

    .service.row
      .col-sm-4
        - path = service_path('certification')
        a[
          class=link_status(path)
          href=path
        ]
          .icon.icon-certificat[aria-hidden= "true"]
          .title = t 'service.certification.label', default: 'Сертификация'
      .col-sm-4
        - path = service_path('accreditation')
        a[
          class=link_status(path)
          href= path
        ]
          .icon.icon-attestat[aria-hidden= "true"]
          .title = t 'service.accreditation.label', default: 'Аккредитация'
      .col-sm-4
        - path = service_path('development')
        a[
          class=link_status(path)
          href= path
        ]
          .icon.icon-documentation[aria-hidden= "true"]
          .title = t 'service.development.label', default: 'Разработка технической документации'

app/views/application/_messages.html.slim
- if not flash.empty?
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      .alert.alert-dismissible.fade.in[role=(name.to_s == 'notice' ? 'note' : 'alert')
                                       class="alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"]
        button.close[type="button"
                     data-dismiss="alert"
                     aria-label="Close"]
          span[aria-hidden='true'] &times;
        = msg

app/views/application/_navbar.html.slim
.navbar.navbar-light.bg-faded
  .wrapper
    - if request.path == root_path
      span.navbar-brand.text-accent.hidden-lg-up: span.icon.icon-home[aria-hidden='true']
    - else
      a.navbar-brand.hidden-lg-up[href=root_path]: span.icon.icon-home[aria-hidden='true']


    button&button.navbar-toggler.hidden-lg-up[
      data-target= '.navbar .collapse'
      data-toggle= 'collapse'
    ]: span.icon.icon-bars[aria-hidden='true']

    ul.nav.navbar-nav.pull-xs-right
      - if user_signed_in?
        - if current_user.staff?
          li.nav-item
            a.nav-link[href=admin_root_path]: span.icon.icon-cogs[aria-hidden='true']
        /li.nav-item
          = link_to current_user, admin_user_path(current_user), \
            class: 'nav-link'
        li.nav-item
          = link_to destroy_user_session_path, :method => :delete, \
            class: 'nav-link' do
            span.icon.icon-sign-out[aria-hidden='true']
      - else
        /li.nav-item[class=link_status(new_user_registration_path)]
          a.nav-link[href=new_user_registration_path]: span.icon.icon-user-plus[aria-hidden='true']
        li.nav-item[class=link_status(new_user_session_path)]
          a.nav-link[href=new_user_session_path]: span.icon.icon-sign-in[aria-hidden='true']
      li.nav-item.totop.m-l-3
        a.nav-link[
          href='#'
          data-scroll
        ]: span.icon.icon-chevron-up[aria-hidden='true']

    .collapse.navbar-toggleable-md.pull-xs-left@region[aria-expanded="false"]
      ul.nav.navbar-nav
        li.nav-item[class=(request.path == about_path && 'active' || nil)]
          a.nav-link[href=about_path] = t 'static.about.label', default: 'О нас'

        li.nav-item.dropdown[class=link_status(services_path)]
          a.nav-link.dropdown-toggle[
            href="#"
            aria-haspopup='true'
            aria-expanded='false'
            data-toggle='dropdown'
          ] = t 'service.index.label'
          .dropdown-menu
            - _path = service_path('certification')
            a.dropdown-item[
              class=link_status(_path)
              href=_path
            ] = t 'service.certification.label'
            - _path = service_path('accreditation')
            a.dropdown-item[
              class=link_status(_path)
              href=_path
            ] = t 'service.accreditation.label'
            - _path = service_path('development')
            a.dropdown-item[
              class=link_status(_path)
              href=_path
            ] = t 'service.development.label'
            .dropdown-divider
            a.dropdown-item.emulator[
              class=link_status(services_path)
              href=services_path
            ]: span.icon.icon-bars[aria-hidden='true']

        li.nav-item.m-r-1[class=link_status(partners_path)]
          a.nav-link[href=partners_path] = t 'partner.index.label'

        li.nav-item.m-r-1[class=link_status(faq_path)]
          a.nav-link[href=faq_path] = t 'static.faq.label'

        li.nav-item.m-r-1[class=link_status(articles_path)]
          a.nav-link[href=articles_path] = t 'article.index.label'

        li.nav-item.m-r-1[class=link_status(contact_path)]
          a.nav-link[href=contact_path] = t 'contact.show.label'

app/views/application/_yandex.search.html.slim
- if YANDEX[:search]
  form#yandex-search.form-search.m-b-1[
    name="yandex-search"
    action="//yandex.ru/sitesearch"
    method="get"
    target='_blank'
    accept-charset='utf-8'
  ]

    input&hidden[
      name='searchid'
      value=YANDEX[:search]
    ]

    input&hidden[
      name='l10n'
      value='ru'
    ]

    input&hidden[
      name='reqenc'
      value=''
    ]

    .input-group
      input&search.form-control[
        name='text'
        list='yandex-search-datalist'
        placeholder='поиск по сайту'
        pattern='.{5,}'
        title='не менее 5 символов'
        required=true
        value=''
      ]

      datalist#yandex-search-datalist
        option value='аттестат'
        option value='аттестация'
        option value='сертификат'
        option value='сертификация'
        option value='эксперт'
        option value='экспертиза'

      span.input-group-btn
        button&submit.btn.btn-link: span.icon.icon-search.text-href[aria-hidden='true']